using System.Collections;
using System.Collections.Generic;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class AnimatorSyncModel
{
    [RealtimeProperty(1, true, true)]
    private string _trigger;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class AnimatorSyncModel : RealtimeModel {
    public string trigger {
        get {
            return _triggerProperty.value;
        }
        set {
            if (_triggerProperty.value == value) return;
            _triggerProperty.value = value;
            InvalidateReliableLength();
            FireTriggerDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(AnimatorSyncModel model, T value);
    public event PropertyChangedHandler<string> triggerDidChange;
    
    public enum PropertyID : uint {
        Trigger = 1,
    }
    
    #region Properties
    
    private ReliableProperty<string> _triggerProperty;
    
    #endregion
    
    public AnimatorSyncModel() : base(null) {
        _triggerProperty = new ReliableProperty<string>(1, _trigger);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _triggerProperty.UnsubscribeCallback();
    }
    
    private void FireTriggerDidChange(string value) {
        try {
            triggerDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _triggerProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _triggerProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Trigger: {
                    changed = _triggerProperty.Read(stream, context);
                    if (changed) FireTriggerDidChange(trigger);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _trigger = trigger;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
