using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class SceneChangerSyncModel
{
    [RealtimeProperty(1, true, true)]
    private string _currentScene;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class SceneChangerSyncModel : RealtimeModel {
    public string currentScene {
        get {
            return _currentSceneProperty.value;
        }
        set {
            if (_currentSceneProperty.value == value) return;
            _currentSceneProperty.value = value;
            InvalidateReliableLength();
            FireCurrentSceneDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(SceneChangerSyncModel model, T value);
    public event PropertyChangedHandler<string> currentSceneDidChange;
    
    public enum PropertyID : uint {
        CurrentScene = 1,
    }
    
    #region Properties
    
    private ReliableProperty<string> _currentSceneProperty;
    
    #endregion
    
    public SceneChangerSyncModel() : base(null) {
        _currentSceneProperty = new ReliableProperty<string>(1, _currentScene);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _currentSceneProperty.UnsubscribeCallback();
    }
    
    private void FireCurrentSceneDidChange(string value) {
        try {
            currentSceneDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _currentSceneProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _currentSceneProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.CurrentScene: {
                    changed = _currentSceneProperty.Read(stream, context);
                    if (changed) FireCurrentSceneDidChange(currentScene);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _currentScene = currentScene;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
