using Glitch9.Editor;
using Glitch9.Internal;
using Glitch9.IO.Networking.RESTApi;
using Glitch9.ScriptableObjects;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace Glitch9.AIDevKit.Editor
{
    internal class AIDevKitSettingsProvider : ExtendedSettingsProvider<AIDevKitSettingsProvider, AIDevKitSettings>
    {
        private static readonly string kDefaultRuntimePath = Path.Combine(Application.persistentDataPath, "Generated");

        private static class Labels
        {
            internal static readonly GUIContent EnablePromptHistoryOnRuntime = new("Prompt History On Runtime",
                "If enabled, all generation requests will be saved in your 'PromptHistory.asset' file. If disabled, you need to call '.EnablePromptHistory()' with your GENTask to save the requests.");
            internal static readonly GUIContent GenerratedFilesPath = new("Generated Files Path",
                "The default path where the generated files will be saved. This is used for generated contents downloads, such as images, audio, and other assets.");
            internal static readonly GUIContent LogLevel = new("Log Level",
                "The log level determines the verbosity of the logs generated by the AIDevKit. You can choose to log different aspects of the requests and responses.");
            internal static readonly GUIContent DisplayCurrency = new("Display Currency",
                "The currency used to display the prices in the AIDevKit.");

            // AutoUpdate Modelsand Delete Deprecated Models
            internal static readonly GUIContent AutoUpdateModels = new("Auto Update Models",
                "If enabled, the AIDevKit will automatically update the models when Unity starts (once per day).");
            internal static readonly GUIContent AutoDeleteDeprecatedModels = new("Auto Delete Deprecated Models",
                "If enabled, the AIDevKit will automatically delete deprecated models when updating the models.");
        }

        protected static HashSet<string> Keywords { get; } = new()
        {
            "AI",
            "LLM",
            "GenAI",
            "Tools",
            "CodeGen",
        };

        private const int SPACE = 10;
        private const int LABEL_WIDTH = 240;


        [SettingsProvider]
        public static SettingsProvider CreateSettingsProvider()
        {
            AIDevKitSettingsProvider provider = new(AIDevKitEditor.Providers.BasePath, SettingsScope.User)
            {
                deactivateHandler = DeactivateHandler,
                keywords = Keywords
            };
            return provider;
        }

        private static void DeactivateHandler()
        {
            AIDevKitSettings.Instance.SaveAsset();
        }

        // Settings Properties ---------------------------------------------------------------
        private SerializedProperty defaultLLM;
        private SerializedProperty defaultIMG;
        private SerializedProperty defaultVID;
        private SerializedProperty defaultTTS;
        private SerializedProperty defaultSTT;
        private SerializedProperty defaultEMB;
        private SerializedProperty defaultMOD;
        private SerializedProperty defaultVoice;
        private SerializedProperty outputPath;
        private SerializedProperty componentGenerator;
        private SerializedProperty scriptDebugger;
        private SerializedProperty logLevel;
        private SerializedProperty requestTimeout;
        private SerializedProperty promptHistoryOnRuntime;

        // Project Context -------------------------------------------------------------------
        private SerializedProperty projectPath;
        private SerializedProperty projectContext;
        private SerializedProperty mainPlatform;
        private SerializedProperty languageTone;
        private SerializedProperty artStyle;
        private SerializedProperty gameGenre;
        private SerializedProperty gameTheme;
        private SerializedProperty description;
        private SerializedProperty is2D;
        private SerializedProperty isMultiplayer;
        private SerializedProperty isVR; // Not used in the settings, but can be added later if needed

        // Local Variables ---------------------------------------------------------------
        private readonly EPrefs<int> _savedLogLevel = new("AIDevKit.LogLevel", (int)RESTLogLevel.RequestEndpoint);

        // Project Context bool list for Switch UI
        private bool[] _gameTypeValues;


        public AIDevKitSettingsProvider(string path, SettingsScope scope = SettingsScope.User) : base(path, scope) { }

        protected override void InitializeSettings()
        {
            // Load the settings properties
            defaultLLM = serializedObject.FindProperty(nameof(defaultLLM));
            defaultIMG = serializedObject.FindProperty(nameof(defaultIMG));
            defaultVID = serializedObject.FindProperty(nameof(defaultVID));
            defaultTTS = serializedObject.FindProperty(nameof(defaultTTS));
            defaultSTT = serializedObject.FindProperty(nameof(defaultSTT));
            defaultEMB = serializedObject.FindProperty(nameof(defaultEMB));
            defaultMOD = serializedObject.FindProperty(nameof(defaultMOD));
            defaultVoice = serializedObject.FindProperty(nameof(defaultVoice));

            outputPath = serializedObject.FindProperty(nameof(outputPath));
            componentGenerator = serializedObject.FindProperty(nameof(componentGenerator));
            scriptDebugger = serializedObject.FindProperty(nameof(scriptDebugger));
            logLevel = serializedObject.FindProperty(nameof(logLevel));
            requestTimeout = serializedObject.FindProperty(nameof(requestTimeout));
            promptHistoryOnRuntime = serializedObject.FindProperty(nameof(promptHistoryOnRuntime));

            projectPath = serializedObject.FindProperty(nameof(projectPath));
            projectContext = serializedObject.FindProperty(nameof(projectContext));

            mainPlatform = projectContext.FindPropertyRelative(nameof(mainPlatform));
            languageTone = projectContext.FindPropertyRelative(nameof(languageTone));
            artStyle = projectContext.FindPropertyRelative(nameof(artStyle));
            gameGenre = projectContext.FindPropertyRelative(nameof(gameGenre));
            gameTheme = projectContext.FindPropertyRelative(nameof(gameTheme));
            description = projectContext.FindPropertyRelative(nameof(description));
            is2D = projectContext.FindPropertyRelative(nameof(is2D));
            isMultiplayer = projectContext.FindPropertyRelative(nameof(isMultiplayer));
            isVR = projectContext.FindPropertyRelative(nameof(isVR));


            if (!AIDevKitConfig.IsPro)
            {
                componentGenerator.boolValue = false;
                scriptDebugger.boolValue = false;
            }

            // Initialize the game type values for the Switch UI
            _gameTypeValues = new bool[]
            {
                is2D.boolValue,
                isMultiplayer.boolValue,
                isVR.boolValue
            };
        }

        protected override void DrawSettings()
        {
            EditorGUIUtility.labelWidth = LABEL_WIDTH;

            DrawGeneralSettings();

            GUILayout.Space(SPACE);

            DrawEditorSettings();

            GUILayout.Space(SPACE);

            DrawNetworkSettings();

            GUILayout.Space(SPACE);

            DrawDefaultModelApis();

            GUILayout.Space(SPACE);

            DrawProjectContext();

            GUILayout.Space(SPACE);


            ExGUIPreset.TroubleShootings(AIDevKitEditor.OnlineDocUrl, EditorConfig.GithubSupportUrl);

            EditorGUIUtility.labelWidth = 0;
        }

        private void DrawGeneralSettings()
        {
            ExGUILayout.BeginSection("General Settings");
            {
                AIDevKitEditorSettings.AutoUpdateModels = EditorGUILayout.Toggle(Labels.AutoUpdateModels, AIDevKitEditorSettings.AutoUpdateModels);

                if (AIDevKitEditorSettings.AutoUpdateModels)
                {
                    EditorGUI.indentLevel++;
                    AIDevKitEditorSettings.AutoDeleteDeprecatedModels = EditorGUILayout.Toggle(Labels.AutoDeleteDeprecatedModels, AIDevKitEditorSettings.AutoDeleteDeprecatedModels);
                    EditorGUI.indentLevel--;
                }

                string runtimePath = ExGUILayout.PathField(Labels.GenerratedFilesPath, outputPath.stringValue, Application.persistentDataPath, kDefaultRuntimePath);
                //string editorPath = ExGUILayout.PathField(Labels.EditorPath, editorOutputPath.stringValue, Application.dataPath, kDefaultEditorPath);

                EditorGUILayout.PropertyField(promptHistoryOnRuntime, Labels.EnablePromptHistoryOnRuntime);

                if (runtimePath != outputPath.stringValue)
                {
                    // check if the path is relative to the persistent data path
                    if (!Path.IsPathRooted(runtimePath) && !runtimePath.StartsWith(Application.persistentDataPath))
                    {
                        Debug.LogWarning($"The runtime path '{runtimePath}' is not relative to the persistent data path '{Application.persistentDataPath}'. " +
                                         "Please enter a valid path relative to the persistent data path.");
                        outputPath.stringValue = kDefaultRuntimePath;
                    }
                    else
                    {
                        outputPath.stringValue = runtimePath;
                    }

                    outputPath.serializedObject.ApplyModifiedProperties();
                }

            }
            ExGUILayout.EndSection();
        }

        private void DrawEditorSettings()
        {
            ExGUILayout.BeginSection("Editor Settings");
            {
                AIDevKitEditor.DisplayedCurrencyCode = ExGUILayout.ResettableEnumPopup(Labels.DisplayCurrency, AIDevKitEditor.DisplayedCurrencyCode, CurrencyCode.USD);

                EditorGUI.BeginDisabledGroup(!AIDevKitConfig.IsPro);
                {
                    // 프로젝트 경로 (Project Path)
                    // AIDevKit Assistant 등이 자동으로 스크립트 오류를 해결하려고할때,
                    // 유저가 만든 스크립트가 아닌 것들을 제외하기 위해, 
                    // 프로젝트 경로를 설정할 수 있도록 합니다.
                    string projectPathValue = ExGUILayout.PathField(new GUIContent("Project Path",
                        "The project path is used to determine the root path of your Unity project. " +
                        "This is used to resolve script paths and other project-related paths."), projectPath.stringValue, Application.dataPath, Application.dataPath);

                    if (projectPathValue != projectPath.stringValue)
                    {
                        // check if the path is relative to the data path
                        if (!Path.IsPathRooted(projectPathValue) && !projectPathValue.StartsWith(Application.dataPath))
                        {
                            Debug.LogWarning($"The project path '{projectPathValue}' is not relative to the data path '{Application.dataPath}'. " +
                                             "Please enter a valid path relative to the data path.");
                            projectPath.stringValue = Application.dataPath;
                        }
                        else
                        {
                            projectPath.stringValue = projectPathValue;
                        }

                        projectPath.serializedObject.ApplyModifiedProperties();
                    }

                    EditorGUILayout.PropertyField(componentGenerator, new GUIContent("Component Generator (Pro Only)",
                        "The Component Generator adds a 'Generate Component' button under 'Add Component' in the Inspector window." +
                        "This button will generate a new component script based on your prompt."));

                    EditorGUILayout.PropertyField(scriptDebugger, new GUIContent("Script Debugger (Pro Only)",
                        "The Script Debugger adds a 'Debug Script' button under script preview in the Inspector window." +
                        "This button will generate a new script based on your prompt and debug it."));

                    if (!componentGenerator.boolValue)
                    {
                        EditorGUILayout.HelpBox("The Component Generator is disabled. Enable it to see the 'Generate Component' button in the Inspector window.", MessageType.None);
                    }

                    if (!scriptDebugger.boolValue)
                    {
                        EditorGUILayout.HelpBox("The Script Debugger is disabled. Enable it to see the 'Debug Script' button in the Inspector window.", MessageType.None);
                    }
                }
                EditorGUI.EndDisabledGroup();
            }
            ExGUILayout.EndSection();
        }

        private void DrawNetworkSettings()
        {
            ExGUILayout.BeginSection("Network Settings");
            {
                EditorGUILayout.PropertyField(requestTimeout, new GUIContent("Request Timeout", "The timeout for the requests in seconds."));

                EditorGUI.BeginDisabledGroup(AIDevKitDebug.kDebugMode.Value);
                {
                    EditorGUILayout.PropertyField(logLevel, Labels.LogLevel);
                }
                EditorGUI.EndDisabledGroup();

                bool newDebugMode = EditorGUILayout.Toggle("Debug Mode", AIDevKitDebug.kDebugMode.Value);

                if (newDebugMode != AIDevKitDebug.kDebugMode.Value)
                {
                    AIDevKitDebug.kDebugMode.Value = newDebugMode;

                    if (newDebugMode)
                    {
                        AIDevKitDebug.kDebugMode.Value = true;
                        _savedLogLevel.Value = logLevel.intValue;
                        _savedLogLevel.Save();
                        logLevel.intValue = (int)RESTLogLevel.All;
                        logLevel.serializedObject.ApplyModifiedProperties();
                    }
                    else
                    {
                        AIDevKitDebug.kDebugMode.Value = false;
                        logLevel.intValue = _savedLogLevel.Value;
                        logLevel.serializedObject.ApplyModifiedProperties();
                    }
                }
            }
            ExGUILayout.EndSection();
        }

        private void DrawDefaultModelApis()
        {
            ExGUILayout.BeginSection(GUIContents.DefaultModelsSectionTitle);
            {
                AIDevKitGUI.LLMPopup(defaultLLM, Api.All, GUIContents.DefaultLLM);
                AIDevKitGUI.EMBPopup(defaultEMB, Api.All, GUIContents.DefaultEMB);
                AIDevKitGUI.MODPopup(defaultMOD, Api.All, GUIContents.DefaultMOD);
            }
            ExGUILayout.EndSection();

            ExGUILayout.BeginSection(GUIContents.DefaultMediaModelsSectionTitle);
            {
                AIDevKitGUI.IMGPopup(defaultIMG, Api.All, GUIContents.DefaultIMG);
                AIDevKitGUI.VIDPopup(defaultVID, Api.All, GUIContents.DefaultVID);
            }
            ExGUILayout.EndSection();

            ExGUILayout.BeginSection(GUIContents.DefaultAudioModelsAndVoiceSectionTitle);
            {
                AIDevKitGUI.TTSPopup(defaultTTS, Api.All, GUIContents.DefaultTTS);
                AIDevKitGUI.STTPopup(defaultSTT, Api.All, GUIContents.DefaultSTT);
                AIDevKitGUI.VoicePopup(defaultVoice, Api.All, GUIContents.DefaultVoice);
            }
            ExGUILayout.EndSection();
        }

        private void DrawProjectContext()
        {
            ExGUILayout.BeginSection("Project Context");
            {
                //EditorGUILayout.PropertyField(mainPlatform, new GUIContent("Main Platform", "The default platform for the project."));
                ExEditorGUI.EnumToggle<Platform>(
                    new GUIContent("Main Platform", "The main platform for the project. This is used to determine the default platform for the project."),
                    mainPlatform);

                //EditorGUILayout.PropertyField(languageTone, new GUIContent("Language Tone", "The tone of the language used in the project."));
                ExEditorGUI.EnumToggle<LanguageTone>(
                    new GUIContent("Language Tone", "The tone of the language used in the project. This is used to determine the default tone for the project."),
                    languageTone);

                //EditorGUILayout.PropertyField(artStyle, new GUIContent("Game Art Style", "The art style of the project. Select all that apply."));
                ExEditorGUI.EnumFlagToggle<ArtStyle>(
                    new GUIContent("Game Art Style", "The art style of the project. This is used to determine the default art style for the project."),
                    artStyle);

                EditorGUILayout.PropertyField(gameTheme, new GUIContent("Game Theme", "The lore setting of the game."));
                EditorGUILayout.PropertyField(gameGenre, new GUIContent("Game Genre (Select All)", "The genre of this game. Select all that apply."));

                // EditorGUILayout.PropertyField(is2D, new GUIContent("Is 2D", "Is the game a 2D game?"));
                // EditorGUILayout.PropertyField(isVR, new GUIContent("Is VR", "Is the game a VR game?"));
                // EditorGUILayout.PropertyField(isMultiplayer, new GUIContent("Is Multiplayer", "Is the game a multiplayer game?"));

                bool[] newValues = ExGUILayout.ToggleGroup(new GUIContent(
                    "Game Type (Select All)",
                    "Select the game type(s) that apply to your project."),
                    new[] { "2D", "Multiplayer", "VR" },
                    _gameTypeValues);

                if (newValues != _gameTypeValues)
                {
                    _gameTypeValues = newValues;
                    is2D.boolValue = _gameTypeValues[0];
                    isMultiplayer.boolValue = _gameTypeValues[1];
                    isVR.boolValue = _gameTypeValues[2];

                    // Apply the changes to the serialized properties
                    is2D.serializedObject.ApplyModifiedProperties();
                    isMultiplayer.serializedObject.ApplyModifiedProperties();
                    isVR.serializedObject.ApplyModifiedProperties();
                }

                const float height = 80f;
                ExEditorGUI.ExpandableTextField("Project Description", description, null, GUILayout.Height(height));
            }
            ExGUILayout.EndSection();
        }
    }
}