using Glitch9.IO.Networking.RESTApi;

namespace Glitch9
{
    public enum Country
    {
        [ApiEnum("Asia/Afghanistan", "AF")] Afghanistan,
        [ApiEnum("Europe/Åland Islands", "AX")] Aaland_Islands,
        [ApiEnum("Europe/Albania", "AL")] Albania,
        [ApiEnum("Africa/Algeria", "DZ")] Algeria,
        [ApiEnum("Oceania/American Samoa", "AS")] American_Samoa,
        [ApiEnum("Europe/Andorra", "AD")] Andorra,
        [ApiEnum("Africa/Angola", "AO")] Angola,
        [ApiEnum("America/Anguilla", "AI")] Anguilla,
        [ApiEnum("Antarctica/Antarctica", "AQ")] Antarctica,
        [ApiEnum("America/Antigua and Barbuda", "AG")] Antigua_and_Barbuda,
        [ApiEnum("America/Argentina", "AR")] Argentina,
        [ApiEnum("Asia/Armenia", "AM")] Armenia,
        [ApiEnum("America/Australia", "AU")] Australia,
        [ApiEnum("Europe/Austria", "AT")] Austria,
        [ApiEnum("Asia/Azerbaijan", "AZ")] Azerbaijan,
        [ApiEnum("America/Bahamas", "BS")] Bahamas,
        [ApiEnum("Asia/Bahrain", "BH")] Bahrain,
        [ApiEnum("Asia/Bangladesh", "BD")] Bangladesh,
        [ApiEnum("America/Barbados", "BB")] Barbados,
        [ApiEnum("Europe/Belarus", "BY")] Belarus,
        [ApiEnum("Europe/Belgium", "BE")] Belgium,
        [ApiEnum("America/Belize", "BZ")] Belize,
        [ApiEnum("Africa/Benin", "BJ")] Benin,
        [ApiEnum("Asia/Bhutan", "BT")] Bhutan,
        [ApiEnum("America/Bolivia Plurinational State of", "BO")] Bolivia_Plurinational_State_of,
        [ApiEnum("Europe/Bosnia and Herzegovina", "BA")] Bosnia_and_Herzegovina,
        [ApiEnum("Africa/Botswana", "BW")] Botswana,
        [ApiEnum("America/Brazil", "BR")] Brazil,
        [ApiEnum("Asia/Brunei Darussalam", "BN")] Brunei_Darussalam,
        [ApiEnum("Europe/Bulgaria", "BG")] Bulgaria,
        [ApiEnum("Africa/Burkina Faso", "BF")] Burkina_Faso,
        [ApiEnum("Africa/Burundi", "BI")] Burundi,
        [ApiEnum("Africa/Cabo Verde", "CV")] Cabo_Verde,
        [ApiEnum("Asia/Cambodia", "KH")] Cambodia,
        [ApiEnum("Africa/Cameroon", "CM")] Cameroon,
        [ApiEnum("America/Canada", "CA")] Canada,
        [ApiEnum("Africa/Central African Republic", "CF")] Central_African_Republic,
        [ApiEnum("Africa/Chad", "TD")] Chad,
        [ApiEnum("America/Chile", "CL")] Chile,
        [ApiEnum("Asia/China", "CN")] China,
        [ApiEnum("America/Colombia", "CO")] Colombia,
        [ApiEnum("Africa/Comoros", "KM")] Comoros,
        [ApiEnum("Africa/Congo", "CG")] Congo,
        [ApiEnum("Africa/Congo Democratic Republic of the", "CD")] Congo_Democratic_Republic_of_the,
        [ApiEnum("America/Costa Rica", "CR")] Costa_Rica,
        [ApiEnum("Africa/Côte d'Ivoire", "CI")] Côte_d_Ivoire,
        [ApiEnum("Europe/Croatia", "HR")] Croatia,
        [ApiEnum("America/Cuba", "CU")] Cuba,
        [ApiEnum("Asia/Cyprus", "CY")] Cyprus,
        [ApiEnum("Europe/Czechia", "CZ")] Czechia,
        [ApiEnum("Europe/Denmark", "DK")] Denmark,
        [ApiEnum("Africa/Djibouti", "DJ")] Djibouti,
        [ApiEnum("America/Dominica", "DM")] Dominica,
        [ApiEnum("America/Dominican Republic", "DO")] Dominican_Republic,
        [ApiEnum("America/Ecuador", "EC")] Ecuador,
        [ApiEnum("Africa/Egypt", "EG")] Egypt,
        [ApiEnum("America/El Salvador", "SV")] El_Salvador,
        [ApiEnum("Africa/Equatorial Guinea", "GQ")] Equatorial_Guinea,
        [ApiEnum("Africa/Eritrea", "ER")] Eritrea,
        [ApiEnum("Europe/Estonia", "EE")] Estonia,
        [ApiEnum("Africa/Eswatini", "SZ")] Eswatini,
        [ApiEnum("Africa/Ethiopia", "ET")] Ethiopia,
        [ApiEnum("Oceania/Fiji", "FJ")] Fiji,
        [ApiEnum("Europe/Finland", "FI")] Finland,
        [ApiEnum("Europe/France", "FR")] France,
        [ApiEnum("Africa/Gabon", "GA")] Gabon,
        [ApiEnum("Africa/Gambia", "GM")] Gambia,
        [ApiEnum("Asia/Georgia", "GE")] Georgia,
        [ApiEnum("Europe/Germany", "DE")] Germany,
        [ApiEnum("Africa/Ghana", "GH")] Ghana,
        [ApiEnum("Europe/Greece", "GR")] Greece,
        [ApiEnum("America/Grenada", "GD")] Grenada,
        [ApiEnum("America/Guatemala", "GT")] Guatemala,
        [ApiEnum("Africa/Guinea", "GN")] Guinea,
        [ApiEnum("Africa/Guinea-Bissau", "GW")] Guinea_Bissau,
        [ApiEnum("America/Guyana", "GY")] Guyana,
        [ApiEnum("America/Haiti", "HT")] Haiti,
        [ApiEnum("Europe/Holy See", "VA")] Holy_See,
        [ApiEnum("America/Honduras", "HN")] Honduras,
        [ApiEnum("Europe/Hungary", "HU")] Hungary,
        [ApiEnum("Europe/Iceland", "IS")] Iceland,
        [ApiEnum("Asia/India", "IN")] India,
        [ApiEnum("Asia/Indonesia", "ID")] Indonesia,
        [ApiEnum("Asia/Iran Islamic Republic of", "IR")] Iran_Islamic_Republic_of,
        [ApiEnum("Asia/Iraq", "IQ")] Iraq,
        [ApiEnum("Europe/Ireland", "IE")] Ireland,
        [ApiEnum("Asia/Israel", "IL")] Israel,
        [ApiEnum("Europe/Italy", "IT")] Italy,
        [ApiEnum("America/Jamaica", "JM")] Jamaica,
        [ApiEnum("Asia/Japan", "JP")] Japan,
        [ApiEnum("Asia/Jordan", "JO")] Jordan,
        [ApiEnum("Asia/Kazakhstan", "KZ")] Kazakhstan,
        [ApiEnum("Africa/Kenya", "KE")] Kenya,
        [ApiEnum("Oceania/Kiribati", "KI")] Kiribati,
        [ApiEnum("Asia/Korea Democratic People's Republic of", "KP")] Korea_Democratic_Peoples_Republic_of,
        [ApiEnum("Asia/Korea Republic of", "KR")] Korea_Republic_of,
        [ApiEnum("Asia/Kuwait", "KW")] Kuwait,
        [ApiEnum("Asia/Kyrgyzstan", "KG")] Kyrgyzstan,
        [ApiEnum("Asia/Lao People's Democratic Republic", "LA")] Lao_Peoples_Democratic_Republic,
        [ApiEnum("Europe/Latvia", "LV")] Latvia,
        [ApiEnum("Asia/Lebanon", "LB")] Lebanon,
        [ApiEnum("Africa/Lesotho", "LS")] Lesotho,
        [ApiEnum("Africa/Liberia", "LR")] Liberia,
        [ApiEnum("Africa/Libya", "LY")] Libya,
        [ApiEnum("Europe/Liechtenstein", "LI")] Liechtenstein,
        [ApiEnum("Europe/Lithuania", "LT")] Lithuania,
        [ApiEnum("Europe/Luxembourg", "LU")] Luxembourg,
        [ApiEnum("Asia/Madagascar", "MG")] Madagascar,
        [ApiEnum("Africa/Malawi", "MW")] Malawi,
        [ApiEnum("Asia/Malaysia", "MY")] Malaysia,
        [ApiEnum("Asia/Maldives", "MV")] Maldives,
        [ApiEnum("Africa/Mali", "ML")] Mali,
        [ApiEnum("Europe/Malta", "MT")] Malta,
        [ApiEnum("Oceania/Marshall Islands", "MH")] Marshall_Islands,
        [ApiEnum("Africa/Mauritania", "MR")] Mauritania,
        [ApiEnum("Africa/Mauritius", "MU")] Mauritius,
        [ApiEnum("Africa/Morocco", "MA")] Morocco,
        [ApiEnum("Africa/Mozambique", "MZ")] Mozambique,
        [ApiEnum("Asia/Myanmar", "MM")] Myanmar,
        [ApiEnum("Africa/Namibia", "NA")] Namibia,
        [ApiEnum("Oceania/Nauru", "NR")] Nauru,
        [ApiEnum("Asia/Nepal", "NP")] Nepal,
        [ApiEnum("Europe/Netherlands", "NL")] Netherlands,
        [ApiEnum("Oceania/New Zealand", "NZ")] New_Zealand,
        [ApiEnum("America/Nicaragua", "NI")] Nicaragua,
        [ApiEnum("Africa/Niger", "NE")] Niger,
        [ApiEnum("Africa/Nigeria", "NG")] Nigeria,
        [ApiEnum("Europe/North Macedonia", "MK")] North_Macedonia,
        [ApiEnum("Europe/Norway", "NO")] Norway,
        [ApiEnum("Asia/Oman", "OM")] Oman,
        [ApiEnum("Asia/Pakistan", "PK")] Pakistan,
        [ApiEnum("Oceania/Palau", "PW")] Palau,
        [ApiEnum("Asia/Palestine State of", "PS")] Palestine_State_of,
        [ApiEnum("America/Panama", "PA")] Panama,
        [ApiEnum("Oceania/Papua New Guinea", "PG")] Papua_New_Guinea,
        [ApiEnum("America/Paraguay", "PY")] Paraguay,
        [ApiEnum("America/Peru", "PE")] Peru,
        [ApiEnum("Asia/Philippines", "PH")] Philippines,
        [ApiEnum("Europe/Poland", "PL")] Poland,
        [ApiEnum("Europe/Portugal", "PT")] Portugal,
        [ApiEnum("Asia/Qatar", "QA")] Qatar,
        [ApiEnum("Europe/Republic of Moldova", "MD")] Republic_of_Moldova,
        [ApiEnum("Europe/Romania", "RO")] Romania,
        [ApiEnum("Europe/Russian Federation", "RU")] Russian_Federation,
        [ApiEnum("Africa/Rwanda", "RW")] Rwanda,
        [ApiEnum("America/Saint Kitts and Nevis", "KN")] Saint_Kitts_and_Nevis,
        [ApiEnum("America/Saint Lucia", "LC")] Saint_Lucia,
        [ApiEnum("America/Saint Vincent and the Grenadines", "VC")] Saint_Vincent_and_the_Grenadines,
        [ApiEnum("Oceania/Samoa", "WS")] Samoa,
        [ApiEnum("Europe/San Marino", "SM")] San_Marino,
        [ApiEnum("Africa/Sao Tome and Principe", "ST")] Sao_Tome_and_Principe,
        [ApiEnum("Asia/Saudi Arabia", "SA")] Saudi_Arabia,
        [ApiEnum("Africa/Senegal", "SN")] Senegal,
        [ApiEnum("Africa/Serbia", "RS")] Serbia,
        [ApiEnum("Africa/Seychelles", "SC")] Seychelles,
        [ApiEnum("Africa/Sierra Leone", "SL")] Sierra_Leone,
        [ApiEnum("Asia/Singapore", "SG")] Singapore,
        [ApiEnum("Europe/Slovakia", "SK")] Slovakia,
        [ApiEnum("Europe/Slovenia", "SI")] Slovenia,
        [ApiEnum("Oceania/Solomon Islands", "SB")] Solomon_Islands,
        [ApiEnum("Africa/Somalia", "SO")] Somalia,
        [ApiEnum("Africa/South Africa", "ZA")] South_Africa,
        [ApiEnum("Africa/South Sudan", "SS")] South_Sudan,
        [ApiEnum("Europe/Spain", "ES")] Spain,
        [ApiEnum("Asia/Sri Lanka", "LK")] Sri_Lanka,
        [ApiEnum("Africa/Sudan", "SD")] Sudan,
        [ApiEnum("South America/Suriname", "SR")] Suriname,
        [ApiEnum("Europe/Sweden", "SE")] Sweden,
        [ApiEnum("Europe/Switzerland", "CH")] Switzerland,
        [ApiEnum("Asia/Syrian Arab Republic", "SY")] Syrian_Arab_Republic,
        [ApiEnum("Asia/Tajikistan", "TJ")] Tajikistan,
        [ApiEnum("Africa/United Republic of Tanzania", "TZ")] United_Republic_of_Tanzania,
        [ApiEnum("Asia/Thailand", "TH")] Thailand,
        [ApiEnum("Asia/Timor-Leste", "TL")] Timor_Leste,
        [ApiEnum("Africa/Togo", "TG")] Togo,
        [ApiEnum("Oceania/Tonga", "TO")] Tonga,
        [ApiEnum("North America/Trinidad and Tobago", "TT")] Trinidad_and_Tobago,
        [ApiEnum("Africa/Tunisia", "TN")] Tunisia,
        [ApiEnum("Asia/Turkey", "TR")] Turkey,
        [ApiEnum("Asia/Turkmenistan", "TM")] Turkmenistan,
        [ApiEnum("Oceania/Tuvalu", "TV")] Tuvalu,
        [ApiEnum("Africa/Uganda", "UG")] Uganda,
        [ApiEnum("Europe/Ukraine", "UA")] Ukraine,
        [ApiEnum("Asia/United Arab Emirates", "AE")] United_Arab_Emirates,
        [ApiEnum("America/United States of America", "US")] United_States_of_America,
        [ApiEnum("South America/Uruguay", "UY")] Uruguay,
        [ApiEnum("Asia/Uzbekistan", "UZ")] Uzbekistan,
        [ApiEnum("Oceania/Vanuatu", "VU")] Vanuatu,
        [ApiEnum("America/Venezuela Bolivarian Republic of", "VE")] Venezuela_Bolivarian_Republic_of,
        [ApiEnum("Asia/Viet Nam", "VN")] Viet_Nam,
        [ApiEnum("Africa/Yemen", "YE")] Yemen,
        [ApiEnum("Africa/Zambia", "ZM")] Zambia,
        [ApiEnum("Africa/Zimbabwe", "ZW")] Zimbabwe,

    }
}