using Glitch9.CoreLib.IO.Audio;
using Newtonsoft.Json;

namespace Glitch9.AIDevKit
{
    public class SpeechOutputOptions
    {
        /// <summary>
        /// Parameters for audio output. 
        /// Required when audio output is requested with modalities: ["audio"].
        /// </summary>
        [JsonProperty("format")] public AudioEncoding? Format { get; set; }

        /// <summary>
        /// The voice the model uses to respond. Supported voices are alloy, ash, ballad, coral, echo, fable, nova, onyx, sage, and shimmer.
        /// </summary>
        [JsonProperty("voice")] public string Voice { get; set; }
    }

    public class SpeechOutput
    {
        /// <summary>
        /// Unique identifier for this audio response.
        /// </summary>
        [JsonProperty("id")] public string Id { get; set; }

        /// <summary>
        /// Base64 encoded audio bytes generated by the model, 
        /// in the format specified in the request.
        /// </summary>
        [JsonProperty("data")] public string Data { get; set; }

        /// <summary>
        /// The Unix timestamp (in seconds) for when 
        /// this audio response will no longer be accessible on the server for use in multi-turn conversations.
        /// </summary>
        [JsonProperty("expires_at")] public UnixTime? ExpiresAt { get; set; }

        /// <summary>
        /// Transcript of the audio generated by the model.
        /// </summary>
        [JsonProperty("transcript")] public string Transcript { get; set; }
    }
}